### ISSUE TITLE
hello , dear sir

### ISSUE THREAD

**Issue by lisadaddy** [davidmitesh/davidmitesh-starknetEdu-starknetERC721_solution#1]
hello , dear sir

why the allinone is empty -_-

**Comment by davidmitesh** [comment]
@lisadaddy  Actually, this repo is intended for the solution of the repo: https://github.com/starknet-edu/starknet-erc721. The contract "AllinOne.cairo" is the solution for this exercise: https://github.com/starknet-edu/starknet-cairo-101/blob/main/contracts/ex14.cairo. The work is in progress. It will be completed in 2 days max I guess. Stay tuned! :)

**Comment by davidmitesh** [comment]
@lisadaddy You can find the AllInOne file here : https://github.com/davidmitesh/starknet-cairo-101/blob/main/contracts/AllInOneContract.cairo
